### ISSUE TITLE
Please fix node.js requirement or test setup (node 18 vs node 20 minimum)

### ISSUE THREAD

**Issue by mcm1957** [ThomasPohl/ioBroker.google-spreadsheet#114]
- You require node 18 minimum at package.json (egines clause states >= 18)
- You test the adapter suing node 20 and node 22 ony (test-and-release workflow)

Its OK to support node 20 and 22 only, but requirements and testing must match. So  EITHER

- increase requirements to node 20 minimum (engins >= 20)

OR

- add node 18 to test matrix (again)

Thanks for correction
mcm1957

**Comment by ThomasPohl** [comment]
I had trouble with the performance of the node 18 pipelines. Now it seems to be okay. I added node 18 back to the list.
