### ISSUE TITLE
Daten in bestimmte Zellen schreiben

### ISSUE THREAD

**Issue by xDarix** [ThomasPohl/ioBroker.google-spreadsheet#42]
Hallo Thomas,

ist es auch möglich Daten in bestimmte Zellen zu schreiben?
Und könntest du vielleicht eine Anleitung machen wie die befehle in JavaScript aussehen?

Vlielen Dank.

**Comment by ThomasPohl** [comment]
Hallo @xDarix ,
in eine einzelne Zelle schreiben ist so direkt aktuell nicht möglich. Klingt aber nach einem sinnvollen Feature. Ich werde das als nächstes mit einbauen.
Was möglich ist, ist mit dem append-feature gezielt an einer Stelle im Sheet die Daten anzuhängen. Ich habe das mal [hier](https://github.com/ThomasPohl/ioBroker.google-spreadsheet/blob/feature/documentation/features/append.md) angefangen zu Dokumentieren. Da ich aber die API bisher in erster Linie als Protokoll verwende habe ich da noch nicht so die Erfahrung. Wenn du also feststellst, dass die Google-API sich anders verhält als gedacht, gib mir gerne einen Hinweis. Ich füge das dann zur Dokumentation hinzu.

**Comment by ThomasPohl** [comment]
@xDarix Ich habe eine neue Version (0.3.0) mit der Möglichkeit zum Schreiben und Lesen von einzelnen Zellen eingebaut. Teste es doch mal. Ich bin an deinem Feedback interessiert :)
