### ISSUE TITLE
no blockly code / blocks

### ISSUE THREAD

**Issue by Wattestaebchen** [ThomasPohl/ioBroker.google-spreadsheet#61]
Hello,

after moving my iobroker to a new server and recovering from backup, the google spreadsheet adapter doesn't work as expected.

I noticed first when checking the scripts.

I already uninstalled / reinstalled via npm in /opt/iobroker (several times). An instance can be created, but settings doesn't open, it loads and loads... No script blocks are created, wich ends up in errors editing that scripts.

I haven't found a way to get the adapter/instance running, neither then to reconfigure.

Edit: Running on arm64, Debian 12

**Comment by ThomasPohl** [comment]
Hi @Wattestaebchen ,

I tried to reproduce your problem. When I add the google-spreadsheet adapter to a new iobroker I can see all the blocklys when creating a new script.

Which versions of iobroker, javascript-adapter and google-spreadsheet-adapter did you install?

**Comment by ThomasPohl** [comment]
@Wattestaebchen , I added a screenshot of the settings page I hope that helps. If the problem still exists, you can open a new issue.
