### ISSUE TITLE
Adapter crashes / getcell not working

### ISSUE THREAD

**Issue by Gtal21** [ThomasPohl/ioBroker.google-spreadsheet#83]
Hello,
this blockly:
![grafik](https://github.com/ThomasPohl/ioBroker.google-spreadsheet/assets/172260111/78ade9e9-717c-4f6c-bde6-9ebdc7b2d211)
causes this errorcode:
`<html><body>

host.ioBroker | 2024-06-10 11:25:17.420 | warn | Do not restart adapter system.adapter.google-spreadsheet.0 because restart loop detected
-- | -- | -- | --
host.ioBroker | 2024-06-10 11:25:17.420 | info | Restart adapter system.adapter.google-spreadsheet.0 because enabled
host.ioBroker | 2024-06-10 11:25:17.420 | error | instance system.adapter.google-spreadsheet.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
google-spreadsheet.0 | 2024-06-10 11:25:16.853 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
google-spreadsheet.0 | 2024-06-10 11:25:16.852 | error | Exception-Code: 400: Unable to parse range: 'Test'!'B7'
google-spreadsheet.0 | 2024-06-10 11:25:16.852 | error | Error:  Unable to parse range: 'Test'!'B7'    at Gaxios._request  (/opt/iobroker/node_modules/gaxios/build/src/gaxios.js:141:23)    at  process.processTicksAndRejections  (node:internal/process/task_queues:95:5)    at async JWT.requestAsync  (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:408:18)
google-spreadsheet.0 | 2024-06-10 11:25:16.851 | error | unhandled promise rejection: Unable to parse range: 'Test'!'B7'
google-spreadsheet.0 | 2024-06-10 11:25:16.851 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
google-spreadsheet.0 | 2024-06-10 11:25:16.850 | error | Error while retrieving data from Google Spreadsheet:Error: Unable to parse range: 'Test'!'B7'

</body>
</html>`

Updating Singlecell (same sheet / same cell) is working!
Adapter Version: 0.30
Javascript: 8.4.2
Any idea?

**Comment by ThomasPohl** [comment]
@Gtal21 Thank you for the bug report. Seems like google changed the data format their service accept. I updated the adapter. As soon as the pipeline works again I will release a new version.
