### ISSUE TITLE
Adapter stürtzt ab wenn eine "leere" zelle gelesen wird (ReadCell).

### ISSUE THREAD

**Issue by xDarix** [ThomasPohl/ioBroker.google-spreadsheet#96]
Hallo,
wenn ich eine leere Zelle mit "ReadCell" einlese, stürzt der Adapter ab. 
Wenn in der Zelle etwas steht funktioniert es einwandfrei.

Habe es mit den beiden Methoden ausprobiert:

`sendTo("google-spreadsheet", "readCell", {"sheetName": "Sheet1", "cell": "U24"},(response)=>{log(response);});`

```
try {
    sendTo("google-spreadsheet", "readCell", {"sheetName": "Sheet1", "cell": "U24"},(response)=>{log(response);});
}catch (error) {
    log(error, "warn");
}
```

**Comment by ThomasPohl** [comment]
Hi @xDarix, danke für den Fehlerbericht. Sollte gefixt sein. Sobald die Pipelines für Windows wieder laufen, release ich eine neue Version
